import  {CiMenuKebab} from 'react-icons/ci'
export const data = [
{
    id:'1',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'2',
    growingPlace:'Kobe Forest',
    growingDate:'2023-05-02',
    type:'santica',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'3',
    growingPlace:'Kyoto Forest',
    growingDate:'2023-02-03',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'4',
    growingPlace:'Tokyo',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'5',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'6',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'7',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'8',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'9',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'10',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},
{
    id:'11',
    growingPlace:'Argato',
    growingDate:'2023-05-02',
    type:'tomentosa',
    dimension:'43x9',
    shape:'Round',
    status:'Pending',
    action:<CiMenuKebab/>
},

];